---

- name: "[KODI] [FEDORA] install rpmfusion packages"
  yum:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    update_cache: true
    state: present

- name: "[KODI] [FEDORA] install kodi"
  yum:
    name: kodi
    update_cache: true
    state: present
