---

- name: "[DOCKER] [ARCH] Install docker"
  become: false
  yay:
    name: "{{ docker_package }}"
    state: present
    update_cache: true

- name: "[DOCKER] [ARCH] Install docker-compose"
  become: false
  yay:
    name: "{{ dockercompose_package }}"
    state: present
    update_cache: true
  tags:
    - install_dockercompose
