---

- name: "[DOCKER] install for {{ linux_distribution }}"
  include_tasks: "docker_{{ linux_distribution }}.yml"

- name: "[DOCKER] Adding {{ ansible_user }} to group docker"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: "[DOCKER] Restart Docker"
  systemd:
    name: docker
    enabled: true
    state: restarted

- name: "[DOCKER_COMPOSE] Download Docker Compose binary"
  import_tasks: docker_compose.yml
  when: linux_distribution != "arch"
  tags:
    - dockercompose

- name: "[DIVE] Install Dive"
  block:
    - name: "[DIVE] Get latest version of Dive"
      uri:
        url: "{{ dive_latest_url }}"
      register: dive_response
      when: linux_distribution != "arch"

    - name: "[DIVE] Set urls for Dive packages"
      vars:
        dive_version: "{{ dive_response.json.tag_name }}"
      set_fact:
        dive_deb_package: "https://github.com/wagoodman/dive/releases/download/{{ dive_version }}/dive_{{ dive_version[1:] }}_linux_amd64.deb"
        dive_rpm_package: "https://github.com/wagoodman/dive/releases/download/{{ dive_version }}/dive_{{ dive_version[1:] }}_linux_amd64.rpm"
      when: linux_distribution != "arch"

    - name: "[DIVE] Download Dive"
      include_tasks: "dive_{{ linux_distribution }}.yml"
  tags:
    - dive

- name: "[SECRETHUB] Install Secrethub for {{ linux_distribution | upper }}"
  include_tasks: "secrethub_{{ linux_distribution }}.yml"
  tags:
    - secrethub
