---

- name: "[SECRETHUB] [FEDORA] download repository file"
  get_url:
    url: https://yum.secrethub.io/secrethub.repo
    dest: /etc/yum/repos.d/secrethub.repo

- name: "[SECRETHUB] [FEDORA] install cli"
  yum:
    name: secrethub-cli
    update_cache: true
    state: present
