---

- name: "[FZF] [DEB] install fzf"
  apt:
    name:
      - fzf
      - ripgrep
    update_cache: true
    state: present
  when: linux_distribution == "ubuntu"

- name: "[FZF] [FEDORA] install fzf"
  yum:
    name:
      - fzf
      - ripgrep
    update_cache: true
    state: present
  when: linux_distribution == "fedora"

- name: "[FZF] [ARCH] install fzf"
  pacman:
    name:
      - fzf
      - ripgrep
    state: present
    update_cache: true
  when: linux_distribution == "arch"

- name: "[FZF] add config to shell config file"
  become: false
  blockinfile:
    path: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
    create: true
    block: |
      if type rg &> /dev/null; then
        export FZF_DEFAULT_COMMAND='rg --files'
        export FZF_DEFAULT_OPTS='-m --height 50% --border'
      fi
