---

- name: "[OHMYZSH] Install zsh"
  import_role:
    name: common
    tasks_from: zsh.yml

- name: "[OHMYZSH] Download installation script"
  get_url:
    url: "{{ ohmyzsh_installer }}"
    dest: /tmp/install.sh
    mode: 0755
    timeout: 60
  when: not (from_post_install | default(false))

- name: "[OHMYZSH] replace source repo"
  replace:
    path: /tmp/install.sh
    regexp: "git@github.com:"
    replace: "https://github.com/"
  when: from_post_install | default(false)

- name: "[OHMYZSH] check if previous oh_my_zsh exists"
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzshdir_exists

- name: "[OHMYZSH] Install oh_my_zsh"
  become: false
  become_user: "{{ ansible_user }}"
  environment:
    CHSH: yes
    RUNZSH: yes
  command: /tmp/install.sh --unattended
  when: not ohmyzshdir_exists.stat.exists

- name: "[OHMYZSH] Change $SHELL variable for {{ ansible_user }}"
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: "[OHMYZSH] ZSH config for snap apps in KDE menu"
  lineinfile:
    path: /etc/zsh/zprofile
    line: "emulate sh -c 'source /etc/profile.d/apps-bin-path.sh'"
  when:
    - desktop_environment == "kde"
    - linux_distribution in ['ubuntu', 'debian']

- name: "[OHMYZSH] delete temporal file"
  file:
    path: /tmp/install.sh
    state: absent
