---

- name: "[VIMPLUGINS] get vim version"
  command: vim --version
  changed_when: true
  register: vim_version

- name: "[VIMPLUGINS] set variable vim_version"
  set_fact:
    vim_version: "{{ vim_version.stdout_lines[0].split(' ')[4].split('.')[0] }}"

- name: "[VIMPLUGINS] install vim plugins"
  become: false
  become_user: "{{ ansible_user }}"
  block:
    - name: "[VIMPLUGINS] create plugins directory"
      file:
        path: "{{ ansible_user_dir }}/.vim/bundle"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "[VIMPLUGINS] clone plugin repository"
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"
        clone: true
        key_file: "{{ ssh_dir }}/osmollo"
        accept_hostkey: true
        version: master
      ignore_errors: true

    - name: "[VIMPLUGINS] generate vimrc"
      template:
        src: vimrc.j2
        dest: "{{ ansible_user_dir }}/.vimrc"
        backup: true

    - name: "[VIMPLUGINS] install vim plugins"
      command: "vim +PluginInstall +qall"
  when: vim_version|int >= 8
