---

- name: "[DROPBOX] [FEDORA] get latest dropbox version"
  get_dropbox_latest:
    distro: "{{ linux_distribution }}"
    arch: "{{ ansible_architecture }}"
  register: dropbox_version

- name: "[DROPBOX] [FEDORA] Install Dropbox package"
  vars:
    dropbox_package: "https://www.dropbox.com/download?dl=packages/{{ linux_distribution }}/nautilus-dropbox-{{ dropbox_version.version }}-1.{{ linux_distribution }}.{{ ansible_architecture }}.rpm"
  yum:
    name: "{{ dropbox_package }}"
    state: present
