---

- name: "[SPOTIFY] [FEDORA] Copy repository file"
  copy:
    src: spotify.repo
    dest: /etc/yum.repos.d/fedora-spotify.repo
    mode: 0644
    owner: root
    group: root

- name: "[SPOTIFY] [FEDORA] Install Spotify"
  yum:
    name: spotify-client
    state: present
    update_cache: true
