---

distro_packages:
  - openvpn
  - networkmanager-openvpn
  - libsecret
  - bind-tools
  - net-tools
  - python-libevdev
  - bridge-utils
  - secure-delete

gnome_arch_packages:
  - wireshark-cli
  - vlc

kde_arch_packages: []

xfce_arch_packages: []

python_packages:
  - python3
  - python-pip
  - ipython
  - python-virtualenv

kwalletcli_package: kwalletcli
