---

- name: "[UBUNTU] Check if ansible_version >= 2.8"
  assert:
    that:
      - ansible_version.full >= "2.8"
    fail_msg: "Ansible version must be >= 2.8. Please, ejecute 'ansible-playbook update_ansible.yml --ask-become-pass'"
    success_msg: "OK, your ansible version is {{ ansible_version.full }}"

- name: "[UBUNTU] Delete snap system packages"
  snap:
    name: "{{ bad_snap_packages }}"
    state: absent

- name: "[UBUNTU] Install packages from Ubuntu repositories"
  apt:
    name: "{{ bad_snap_packages }}"
    state: latest
