---

- name: "Check if {{ last_update_file }} exists"
  stat:
    path: "{{ last_update_file }}"
  register: stat_response
  tags:
    - always

- name: "Check if last update was 1 week ago or later"
  find:
    path: "{{ last_update_file | dirname }}"
    hidden: true
    patterns: "^({{ last_update_file | basename }})$"
    use_regex: true
    age: 1w
    file_type: file
  register: lastupdate
  tags:
    - always

- name: "update packages"
  import_tasks: update_packages.yml
  when:
    - not disable_updates
    - (not stat_response.stat.exists) or (lastupdate.files | length == 1)
  tags:
    - always

- name: "disable selinux"
  import_tasks: selinux.yml
  when: linux_distribution == "fedora"
  tags:
    - common
    - disable_selinux

- name: "include vars file for linux distribution"
  include_vars:
    file: "{{ linux_distribution | lower }}.yml"
  tags:
    - common
    - install_packages
    - yay
    - python
    - python3

- name: "include vars file for desktop environment"
  include_vars:
    file: "{{ desktop_environment | lower }}.yml"
  when: desktop_environment is defined
  tags:
    - common
    - install_packages

- name: "install apt-transport-https package"
  apt:
    name: apt-transport-https
    state: present
  when: linux_distribution in ["ubuntu", "debian"]

- name: "install packages"
  include_tasks:
    file: "install_packages_{{ linux_distribution }}.yml"
    apply:
      tags:
        - common
        - install_packages
  tags:
    - common
    - install_packages

- name: "install and configure python"
  import_tasks: python.yml
  tags:
    - common
    - python
    - python3

- name: "delete snap packages"
  import_tasks: delete_snap.yml
  when: ansible_distribution == "ubuntu" and ansible_distribution_major_version >= "18"
  tags:
    - common
    - delete_snap

- name: "install zsh"
  import_tasks: zsh.yml
  tags:
    - common
    - zsh

- name: "[ARCH] install yay package"
  import_tasks: yay.yml
  when: linux_distribution == "arch"
  tags:
    - common
    - yay

- name: "Configure size of bash history"
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  loop:
    - 'export HISTTIMEFORMAT="%d/%m - %H:%M:%S "'
    - 'export HISTSIZE=50000'
  tags:
    - common
    - bash_history_size

- name: "Configure $HOME directories"
  import_tasks: home.yml
  tags:
    - common
    - home

- name: "Configure SSH client"
  import_tasks: ssh_config.yml
  tags:
    - common
    - ssh_config
