---

- name: "[NOMACHINE] include vars file"
  include_vars:
    file: "{{ linux_distribution }}.yml"

- name: "[NOMACHINE] get lastest version of nomachine"
  block:
    - name: "[NOMACHINE] get latest version of no machine"
      get_nomachine_latest:
      register: nomachine_response

    - name: "[NOMACHINE] set variable with latest version of nomachine"
      set_fact:
        nomachine_version: "{{ nomachine_response.version }}"

- name: "[NOMACHINE] install for {{ linux_distribution }}"
  include_tasks: "nomachine_{{ linux_distribution }}.yml"
