---

- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    gpg_keys:
      - "{{ ansible_user_dir }}/home.pub"
      - "{{ ansible_user_dir }}/home.priv"
      - "{{ ansible_user_dir }}/work.pub"
      - "{{ ansible_user_dir }}/work.priv"
      - "{{ ansible_user_dir }}/rootnerds.pub"
  vars_prompt:
    - name: home_gpg
      prompt: Enter personal GPG passphrase
      unsafe: true

    - name: work_gpg
      prompt: Enter work GPG passphrase
      unsafe: true

    - name: rootnerds_gpg
      prompt: Enter rootnerds GPG passphrase
      unsafe: true
  tasks:
    - name: "Check if gpg keys exist"
      stat:
        path: "{{ item }}"
      register: keys_exist
      loop: "{{ gpg_keys }}"

    - name: "Exit if any gpg key doesnt exist"
      vars:
        result: "{{ keys_exist.results | json_query('[].stat.exists') }}"
      assert:
        that:
          - not False in result
        fail_msg: "Any GPG key file doesnt exist: {{ gpg_keys | join(', ') }}"

    - name: "Import gpg public keys from files"
      shell: "gpg --import {{ item }}"
      changed_when: "'sin cambios' not in gpg_response.stderr"
      register: gpg_response
      loop: "{{ gpg_keys }}"
      when: item.endswith('.pub')

    - name: "Import gpg private keys from files"
      shell: "gpg --batch --passphrase {{ lookup('vars', ((item | basename).split('.')[0]) + '_gpg') }} --pinentry-mode loopback --import {{ item }}"
      loop: "{{ gpg_keys }}"
      when: item.endswith('.priv')

    - name: "Trust gpg keys"
      shell: "for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u); do  echo -e '5\ny\n' |  gpg --command-fd 0 --expert --edit-key $fpr trust; done"
