---

- name: "[BEEKEEPER] [DEB] Check if ansible_version >= 2.8"
  assert:
    that:
      - ansible_version.full >= "2.8"
    fail_msg: "Ansible version must be >= 2.8. Please, ejecute 'ansible-playbook update_ansible.yml '"
    success_msg: "OK, your ansible version is {{ ansible_version.full }}"

- name: "[BEEKEEPER] [DEB] Install Beekeeper using snap"
  snap:
    name:
      - beekeeper-studio
    state: present
