---

- name: "Get latest version of Etcher"
  uri:
    url: "{{ etcher_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: etcher_latest

- name: "Set urls for Etcher packages"
  vars:
    etcher_version: "{{ etcher_latest.url | urlsplit('path') | basename }}"
  set_fact:
    etcher_package: "https://github.com/balena-io/etcher/releases/download/{{ etcher_version }}/balena-etcher-electron-{{ etcher_version[1:] }}-linux-x64.zip"

- name: "download etcher"
  unarchive:
    src: "{{ etcher_package }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
