---

- name: "create spotify-tui directory"
  file:
    path: "{{ ansible_user_dir }}/.config/spotify-tui"
    state: directory

- name: "configure spotify tui"
  template:
    src: spotify_tui_config.j2
    dest: "{{ ansible_user_dir }}/.config/spotify-tui/client.yml"
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
