---

- block:
    - name: "[WOEUSB] [UBUNTU] install woeusb repository"
      apt_repository:
        repo: ppa:nilarimogard/webupd8

    - name: "[WOEUSB] [UBUNTU] install woeusb package"
      apt:
        name: woeusb
        state: present
        update_cache: true
  when: code_name == "bionic"
