---

chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
chromium_package: chromium
dropbox_package: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb"
gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.deb"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
vagrant_package: vagrant
virtualbox_packages:
  - virtualbox-6.0
buttercup_deb_package: "{{ buttercup_latest_url.split('/')[0:-1] | join('/') }}/download/{{ buttercup_version }}/buttercup-desktop_{{ buttercup_version | replace('v', '') }}_amd64.deb"
megacmd_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/megacmd-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
megacmd_dependencies:
  - libmediainfo0v5
  - libpcrecpp0v5
  - libzen0v5
  - libcrypto++6
  - libmms0
  - libtinyxml2-6

megasync_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
file_manager_plugin: "{{ lookup('template', 'megasync.j2') | replace('\n', '') }}"
nomachine_package: "https://download.nomachine.com/download/{{ nomachine_version.split('.')[0:2] | join('.') }}/Linux/nomachine_{{ nomachine_version }}_amd64.deb"

vivaldi_package: https://downloads.vivaldi.com/stable/vivaldi-stable_{{ vivaldi_version }}_amd64.deb

protonvpn_dependencies:
  - openvpn
  - dialog
  - python3-pip
  - python3-setuptools

wireguard_packages:
  - wireguard
