---

# forticlientvpn_packages:
#   - openfortivpn
#   - NetworkManager-fortisslvpn
#   - NetworkManager-fortisslvpn-gnome

gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.rpm"
chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_{{ ansible_architecture }}.rpm"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer.{{ ansible_architecture }}.rpm"
nomachine_package: "https://download.nomachine.com/download/{{ nomachine_version.split('.')[0:2] | join('.') }}/Linux/nomachine_{{ nomachine_version }}_{{ ansible_architecture }}.rpm"
woeusb_package:
  v31: "https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Everything/{{ ansible_architecture }}/os/Packages/w/WoeUSB-3.2.12-3.fc{{ fedora_version }}.{{ ansible_architecture }}.rpm"
  v32: "https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Everything/{{ ansible_architecture }}/os/Packages/w/WoeUSB-3.3.1-2.fc{{ fedora_version }}.{{ ansible_architecture }}.rpm"
  v33: "https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Everything/{{ ansible_architecture }}/os/Packages/w/WoeUSB-3.3.1-3.fc{{ fedora_version }}.{{ ansible_architecture }}.rpm"

buttercup_rpm_package: "{{ buttercup_latest_url.split('/')[0:-1] | join('/') }}/download/{{ buttercup_version }}/buttercup-desktop-{{ buttercup_version | replace('v', '') }}.{{ ansible_architecture }}.rpm"

virtualbox_packages:
  - VirtualBox
  - kernel-devel
  - kernel-headers
  - dkms
  - qt5-qtx11extras
  - elfutils-libelf-devel
  - zlib-devel

vagrant_package:
  - vagrant

chromium_package: chromium

megacmd_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}/{{ ansible_architecture }}/megacmd-{{ ansible_distribution }}_{{ ansible_distribution_version }}.{{ ansible_architecture }}.rpm"

megasync_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}/{{ ansible_architecture }}/megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.{{ ansible_architecture }}.rpm"
file_manager_plugin: "{{ lookup('template', 'megasync.j2') | replace('\n', '') }}"

vivaldi_package: https://downloads.vivaldi.com/stable/vivaldi-stable-{{ vivaldi_version }}.{{ ansible_architecture }}.rpm

protonvpn_dependencies:
  - openvpn
  - dialog
  - python3-pip
  - python3-setuptools

wireguard_packages:
  - wireguard-dkms
  - wireguard-tools

typora_dir: /opt/typora
typora_package: https://typora.io/linux/Typora-linux-x64.tar.gz
podman_package: podman
forticlient_rpm_package: "https://filestore.fortinet.com/forticlient/downloads/FortiClientFullVPNInstaller_6.4.0.0851.rpm"
