---

install_docker: true
install_dropbox: true
install_vscode: true
install_spotify: true
install_ohmyzsh: false
install_sublimetext: false
install_atom: false
install_gitkraken: false
install_telegram: true
install_slack: false
install_forticlientvpn: false
install_tlp: false
install_virtualbox: true
install_pycharm: false
install_keepass: false
install_buttercup: false
install_windscribe: false
install_chrome: false
install_teamviewer: true
install_nomachine: false
install_ecs: false
install_postman: false
install_skype: false
install_java: false
install_apachedirectory: false
install_rambox: false
install_franz: false
install_chromium: false
install_deluge: false
install_cherrytree: false
install_k8s_tools: true
install_flatpak: false
install_megacmd: true
install_megasync: false
install_vivaldi: false
install_brave: true
install_bitwarden: false
install_lexnet: false
install_pass: false
install_bucklespring: false
install_protonvpn: true
install_prezto: true
install_etcher: true
install_woeusb: true
install_go: true
install_fzf: true
install_vimplugins: true
install_authy: false
install_yakyak: false
install_hiri: false
install_steam: false
install_wireguard: true
install_typora: true
install_beekeeper: false
intall_kdenlive: true
install_sublimemerge: true
install_bfg: true
install_vscodium: false
install_tmux: false
install_kodi: false
install_mame: false
install_podman: true
install_act: true
install_hashicorp: true
install_vault: true
install_terraform: true
install_consul: false
install_nomad: false
install_zoom: false
install_githubcli: true
install_1password: true
install_secrethub: true
install_mailspring: false
install_obs: false
