---

# forticlientvpn_packages:
#   - openfortivpn
#   - network-manager-fortisslvpn
#   - network-manager-fortisslvpn-gnome

gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.deb"
chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
nomachine_package: "https://download.nomachine.com/download/{{ nomachine_version.split('.')[0:2] | join('.') }}/Linux/nomachine_{{ nomachine_version }}_amd64.deb"

virtualbox_packages:
  - virtualbox-6.0

chromium_package: chromium-browser
vagrant_package: "https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_{{ ansible_architecture }}.deb"
buttercup_deb_package: "{{ buttercup_latest_url.split('/')[0:-1] | join('/') }}/download/{{ buttercup_version }}/buttercup-desktop_{{ buttercup_version | replace('v', '') }}_amd64.deb"
megacmd_package: "https://mega.nz/linux/MEGAsync/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/amd64/megacmd-x{{ ansible_distribution }}_{{ ansible_distribution_version }}_amd64.deb"
megacmd_dependencies:
  - libmediainfo0v5
  - libpcrecpp0v5
  - libzen0v5
  - libcrypto++6
  - libmms0
  - "{{ 'libtinyxml2-6' if ubuntu_codename != 'groovy' else '' }}"

megasync_package: "https://mega.nz/linux/MEGAsync/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/amd64/megasync-x{{ ansible_distribution }}_{{ ansible_distribution_version }}_amd64.deb"
file_manager_plugin: "{{ lookup('template', 'megasync.j2') | replace('\n', '') }}"

vivaldi_package: https://downloads.vivaldi.com/stable/vivaldi-stable_{{ vivaldi_version }}_amd64.deb

protonvpn_dependencies:
  - openvpn
  - dialog
  - python3-pip
  - python3-setuptools

steam_package: http://repo.steampowered.com/steam/archive/precise/steam_latest.deb

wireguard_packages:
  - wireguard

podman_package: podman
