---

- hosts: localhost
  connection: local
  vars:
    git_target: "{{ target | default('all') }}"
  tasks:
    - assert:
        that:
          - git_target in ['all', 'gitlab', 'github']
        fail_msg: "'secrets' variable must be the path of file with access tokens and 'target' variable must be one of these values: all, gitlab or github"

    - name: "find variables files"
      find:
        paths: "."
        patterns: "^.*(yml)$"
        use_regex: true
        recurse: true
        file_type: file
      register: find_response

    - set_fact:
        vars_files: "{{ find_response.files | json_query(id_query) | select('match', '^(roles).*(?:defaults|vars).*(yml)$') | list }}"
      vars:
        id_query: "[].path"

    - include_vars: "{{ item }}"
      vars:
        id_query: "[].path"
      loop: "{{ vars_files }}"

    - include_role:
        name: tools/gitlab_repo
      vars:
        repo_name: "{{ item }}"
        repo_state: absent
        gitlab_token: "{{ gitlab_token_access }}"
      loop:
        - fkrva_argos
        - mlyid_iluvatar
        - mlyid_fsm
        - argos
        - iluvatar
        - msqlm_ops
      when: git_target in ["all", "gitlab"]

    - include_role:
        name: tools/github_repo
      vars:
        repo_name: "{{ item }}"
        repo_state: absent
        github_token: "{{ github_token_access }}"
      loop:
        - fkrva_argos
        - mlyid_iluvatar
        - mlyid_fsm
        - msqlm_ops
      when: git_target in ["all", "github"]
