---

- name: "[LOAD VARS] setting ansible variables"
  import_playbook: playbooks/load_distro_vars.yml
  tags:
    - always

- hosts: localhost
  connection: local
  tasks:
    - name: "check if system is prepared"
      block:
        - name: "check if prepare flag exists"
          stat:
            path: /var/tmp/.prepare
          register: flag_response

        - name: "Exit if system is not prepared"
          fail:
            msg: "Por favor, antes de continuar ejecuta el comando 'ansible-playbook playbooks/prepare.yml'"
          when: not flag_response.stat.exists
      when: linux_distribution in ["debian", "ubuntu"]
      tags:
        - always

###############
# INSTALACION #
###############

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    disable_updates: "{{ lookup('env', 'REPO_DISABLE_UPDATES') | default(false) | bool }}"
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
  roles:
    - common
    - extra_software
    - post_install
