---

- name: "[VIRTUALBOX] check default python version pre installation"
  stat:
    path: /usr/bin/python
  register: pre_response

- name: "[VIRTUALBOX] include vars file"
  include_vars:
    file: "{{ linux_distribution }}.yml"
  tags:
    - vagrant

- name: "[VIRTUALBOX] install virtualbox for {{ linux_distribution }}"
  include_tasks: "virtualbox_{{ linux_distribution }}.yml"

- name: "[VIRTUALBOX] Adding {{ ansible_user }} to group vboxusers"
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: true

- name: "[VIRTUALBOX] Add VAGRANT_DEFAULT_PROVIDER to /etc/profile"
  lineinfile:
    path: /etc/profile
    line: export VAGRANT_DEFAULT_PROVIDER=virtualbox
    state: present

- name: "[VIRTUALBOX] Check if extension pack is already installed"
  command: "VBoxManage list extpacks"
  changed_when: false
  register: extpack_list

- name: "[VIRTUALBOX] Download VirtualBox extension pack"
  get_url:
    url: "{{ virtualbox_extension_package }}"
    dest: /tmp/
    force: yes
  register: download_result
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: "[VIRTUALBOX] Install VirtualBox extension pack"
  command: "echo 'y' | VBoxManage extpack install --replace {{ download_result.dest }}"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: "[VIRTUALBOX] Delete Virtualbox Extension pack"
  file:
    path: "{{ download_result.dest }}"
    state: absent
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: "[VIRTUALBOX] check default python version post installation"
  stat:
    path: /usr/bin/python
  register: post_response

- name: "[VIRTUALBOX] restore python version"
  block:
    - name: "[VIRTUALBOX] delete python link"
      file:
        path: /usr/bin/python
        state: absent

    - name: "[VIRTUALBOX] restore default python version"
      file:
        src: "/usr/bin/{{ pre_response.stat.lnk_target }}"
        dest: "/usr/bin/python"
        state: link

    - name: "Alternative link for python"
      alternatives:
        name: python
        link: /usr/bin/python
        path: "/usr/bin/{{ pre_response.stat.lnk_target }}"
  when:
    - pre_response.stat.lnk_target != post_response.stat.lnk_target
