---

- name: "[VIRTUALBOX] [FEDORA] Import repository key"
  rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: "[VIRTUALBOX] [FEDORA] Create repository file"
  get_url:
    url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo

- name: "[VIRTUALBOX] [FEDORA] Install Virtualbox packages"
  yum:
    name: "{{ virtualbox_packages }}"
    state: present
    update_cache: true

- name: "[VAGRANT] [FEDORA] Install Vagrant"
  yum:
    name: "{{ vagrant_package }}"
    state: present
    update_cache: true
  tags:
    - vagrant

- name: "[VAGRANT] [FEDORA] Uninstall vagrant-libvirt if is installed"
  yum:
    name: vagrant-libvirt
    state: absent
  tags:
    - vagrant
