---

- name: "[WINDSCRIBE] [FEDORA] copy repository file"
  copy:
    src: windscribe.repo
    dest: /etc/yum.repos.d/windscribe.repo

- name: "[WINDSCRIBE] [FEDORA] install windscribe package"
  yum:
    name: windscribe-cli
    state: present
    update_cache: true
