---

- name: "[JAVA] [UBUNTU] install java repository"
  apt_repository:
    validate_certs: no
    repo: 'ppa:openjdk-r/ppa'
    state: present
    codename: "{{ ubuntu_codename }}"

- name: "[JAVA] [UBUNTU] install java package"
  apt:
    name: openjdk-11-jdk
    update_cache: true
    state: latest
