---

- name: "[ATOM] Get latest version of Atom"
  uri:
    url: "{{ atom_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: atom_latest
  when: linux_distribution != "arch"

- name: "[ATOM] Set urls for Atom packages"
  vars:
    atom_version: "{{ atom_latest.url | urlsplit('path') | basename }}"
  set_fact:
    atom_rpm_package: "https://github.com/atom/atom/releases/download/{{ atom_version }}/atom.x86_64.rpm"
    atom_deb_package: "https://github.com/atom/atom/releases/download/{{ atom_version }}/atom-amd64.deb"
  when: linux_distribution != "arch"

- name: "[ATOM] install atom for {{ linux_distribution }}"
  include_tasks: "atom_{{ linux_distribution }}.yml"

- name: "[ATOM] install packages"
  block:
    - name: "[ATOM] get json with packages"
      uri:
        url: "{{ atom_packages_url }}"
      register: packages_response

    - name: "[ATOM] Install packages for Atom"
      become: false
      become_user: "{{ ansible_user }}"
      vars:
        id_query: "[].name"
      command: "apm install {{ item }}"
      loop: "{{ packages_response.json | default([]) | json_query(id_query) | list }}"
  tags:
    - atom_extensions
