---

# TODO: descomentar cuando typora.io deje de dar timeouts
# - name: "[DEB] Import repository key"
#   apt_key:
#     url: https://typora.io/linux/public-key.asc
#     state: present

- name: "[DEB] Import repository key"
  apt_key:
    data: "{{ lookup('file', 'typora.asc') }}"
    state: present

- name: "[DEB] install typora repository"
  apt_repository:
    repo: "deb https://typora.io/linux ./"
    state: present

- name: "[DEB] install typora"
  apt:
    name: typora
    state: present
    update_cache: true
