---

- name: "[DEBIAN] install megasync package"
  apt:
    deb: "{{ megasync_package }}"
    state: present
    update_cache: true

- name: "[DEBIAN] Install megasync for file manager"
  apt:
    deb: "{{ file_manager_plugin }}"
    state: present
  when: file_manager_plugin is defined
